env:
  global:
  - DOCKER_ORG: semitechnologies
  - DOCKER_REPO: contextionary
  - VERSION: 0.1.0
  - secure: eZlMg64iN674fL8nGPjtHD6g8xuad+LtEejud7TeiAm6vl5H53dbuVqqncPalRzqIAOlJqq7c1IHbI62mgekZF2ufHNDCYlXqNL/zUYkUUlaQLmxvdO0HvLbxQEBGF3NLa5DNQ81hw93BTvIL8rGqYsWEaFs6LgLvlpTMhfkXWXSwLiN8hx7s+rVP6OH39kmpJXL2TmLgv/CA82uWJeJSIQUK2vRWhYeQi3m7evf+gr9QAlz2diWkIrrThVcAK+tCb7o1Iv7hsCJqzFGPPKm3IozTW5A8m5kpiVTiXyqSbb2OzA51A8tqoUCgO3f7PyPYdBmt8EmnnhURTUhOR6/TUUU3ueZF9fQIsjbgcTooo4xrt5uWjc2bS79EuYjJAExAvwtNJO+ufHZknFuOisbtB6mRWEwsu5K8kl2hb5WL4bYE5rhoiqillDvcu2H50rpPadP39kysbt/gg2cbwX3a/3o69oEWM5LOlESJbqxjuuXL7HcVXr92vCDlsgMju04W79PiDa8qwdxHWDTYSTkFZQdg0t7yCCosWcxXzKCawNdH7Qfc8z3hy5aTme5oSkYzG1IdklTCAcx16MIsuMWv5BN386nuaTuD3+z+NjSiYVVLyfLlWHj2b6IpVUqdsscLkkP2O/grdoGQHNWpFWxvlhTwYIIT55I90TuWSNv7Ys=
  - secure: FBua8M8ZV40tvzR/Yip8lV78bUTgkM5u/GHLlfKEhFECi2lMu5CmyGXaUSkvJ1gYcavhNB1HJqZXgszsGUo4fCaWb+hp+awW2uzQ4Ff77UZtL99SgnWdt+TtpdrBe/DI8aPI/WZq41FfdZfP/MeFa9FKezPYY/R1IrelxtEO9582tHQMVufQaEiNQrmMAtVqMDsabT9HR46mGg7kxWaqd2nKsuvhL2xyc3y1KlKgMHLoIE8gfyY1x8a1qIZDl61umQLKGNJBT4+ueLJizTVnMSYDPxL9csKzl5w9GwerY4uN2s2DuLt6P/z9D6JOZsT6hXtwAsg8OvyK5bAi54Glhi/E5qAMlHgASS/0trkPxN+in1yWIIEiCyXXA6Zk+Lj3h9KEEt0HL5qU7wrOhYP/6xvwf/8MbyHCp5TKBLuXh3/nBBheKNqsGWqPYDW9mKTtmxwI2Mu9QoSd8h1rjap+TPIezErR8jm4INHTvisjEJQT9X1f5Huk7fqWDAiUfzZ7ShIdMF1/JDJis6BqquDoD5UkFRQyU9cOMkKuMaC+eKpptmEQ2tf6T4axRnxuV8JZDyn1muCMePnSzmT+pA4R7UANhtYKbCoW1HaAI9ouxpx9yhxyXG3+IjqJYTYFl+cQtdlJ4Gq6OiEJGoy6gdf+2cAxwW0J1CFgC+oRlWPXR1w=

language: go

script:
  - TAG=test ./build.sh

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
